Stud/urls.py
from django.urls import include


from .import views
from django.contrib import admin
from django.urls import path
from .import Hod_views, views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin', admin.site.urls),
    path('base', views.Base, name='base'),
    path('home', Hod_views.Home, name='home'),
    path('', views.Accueil, name='acceueil'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('gestionnaire', views.coord, name='gestionnaire'),
    path('decideur', views.deci, name='decideur'),
    path('visiteur', views.visit, name='visiteur'),
    path('peche/', views.peche, name="peche"),
    path('post/<int:id>/', views.detail, name="detail"),
    path('post/', views.all, name="post"),
    path('new_post', views.new_post, name="new_post"),
    path('update_post/<int:pk>/', views.update_post, name="update_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),

    path('ressource/', views.ress, name="ressource"),
    path('upda_res/<int:id>/', views.upda_ress, name="upda_res"),
    path('delete_ress/<int:id>/', views.del_ress, name="delete_ress"),
    path('foncier', views.fonce, name='foncier'),
    path('commune', views.commune, name='commune'),
    path('commune_detail', views.co, name='commune_detail'),
    path('foncier/', include('foncier.urls')),

    # profile

    path('profile_list/', views.profile_list, name='profile_list'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foncier/urls.py
from django.urls import path

from .import views

app_name = 'foncier'


urlpatterns = [
    path('DimFoncier/', views.DimFon, name='DimFoncier'),
    path('DimFoncierGouvernanc/', views.DFG, name='DimFoncierGouvernanc'),
   # path('DimGeographie/', views.DG, name='DimGeographie'),
   # path('FactFoncier/', views.FF, name='FactFoncier'),
  
    path('de_fon<int:id>/', views.delete_fon, name='de_fon'),
    path('up_fon<int:id>/', views.update_fon, name='up_fon'),
    path('de_Gouve<int:id>/', views.delete_up_Gouve, name='de_Gouve'),
    path('up_Gouve<int:id>/', views.update_up_Gouve, name='up_Gouve'),
   # path('up_geo<int:id>/', views.update_geo, name='up_geo'),
    #path('de_geo<int:id>/', views.delete_geo, name='de_geo'),


]

foncier/models.py
from django.utils import timezone
from django.db import models

# foncier


class DimFoncier(models.Model):

    codeCommune = models.IntegerField()
    nomCommune = models.CharField(max_length=300)
    StatuFoncier = models.CharField(max_length=300)
    TerrDeclas5D_Ans = models.CharField(max_length=300)
    ActFonciePresen = models.CharField(max_length=300)
    TxtFoncier = models.CharField(max_length=300)
    OutilGesFoncier = models.CharField(max_length=300)
    TypeConflit = models.CharField(max_length=300)
    TypeUsage = models.CharField(max_length=300)
    ExistCadrConcert = models.CharField(max_length=300)
    EchelCadrConcert = models.CharField(max_length=300)
    Entrepris_Indust_IncidFonc = models.CharField(max_length=300)
    TypeExploit_Foncier = models.CharField(max_length=300)
    SuperficConced = models.DecimalField(max_digits=10, decimal_places=5)
    SuperficExploite = models.DecimalField(max_digits=10, decimal_places=5)
    Superfic_Deja_Exploite = models.DecimalField(
        max_digits=10, decimal_places=5)
    date_en = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):
        return str(self.nomCommune)


class DimFoncierGouvernanc(models.Model):
    codeCommune = models.IntegerField()
    nomCommune = models.CharField(max_length=300)
    LoiReglement = models.CharField(max_length=300)
    OutilSecuriseFoncie = models.CharField(max_length=300)
    ActFoncier = models.CharField(max_length=300)
    DegreConnaissanc = models.CharField(max_length=300)
    NivComprehension = models.CharField(max_length=300)
    Resume = models.CharField(max_length=300)
    AtelierBonInformat = models.CharField(max_length=300)
    SecuritAjout = models.CharField(max_length=300)
    NreConflitAnnComm = models.IntegerField()
    NbreIndustri_FoncComm = models.IntegerField()
    SuperfiAlloueIndustri = models.DecimalField(
        max_digits=10, decimal_places=2)
    NbreIndustri_FoncCommMoy = models.IntegerField()
    SupTypeFoncier = models.DecimalField(max_digits=10, decimal_places=5)
    ActImplique = models.CharField(max_length=300)
    CauseAvance = models.CharField(max_length=300)
    SolutionPropose = models.CharField(max_length=300)
    SolutionRetenu = models.CharField(max_length=300)
    VerificatProcedur = models.CharField(max_length=300)
    ControlPermanant = models.CharField(max_length=300)
    ConfliFoncieEnregMois = models.IntegerField()
    date_ent = models.DateTimeField()
    date_modification = models.DateTimeField()

    def __str__(self):
        return str(self.nomCommune)


class Visiteur (models.Model):
    nom = models.CharField(max_length=25)
    date_visiteur = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom

foncier/views.py
from django.shortcuts import render, redirect
from foncier.DimFoncier import Dimfonfon

from django.contrib import messages
from foncier.DimFoncierGouvernanc import Dimfong



from foncier.models import DimFoncier, DimFoncierGouvernanc

# Create your views here.


def DimFon(request):

    if request.method == 'POST':

        form = Dimfonfon(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/foncier/DimFoncier/')
    else:
        form = Dimfonfon()

    return render(request, 'pag/Dimfon.html', {'form': form, 'dataObject': DimFoncier.objects.all()})


# update Gouver
def update_fon(request, id):
    dataObject = DimFoncier.objects.get(id=id)
    form = Dimfonfon(instance=dataObject)
    if request.method == 'POST':
        form = Dimfonfon(request.POST, instance=dataObject)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/foncier/DimFoncier/')

    context = {

        'form': form

    }
    return render(request, 'pag/Dimfon.html', context)


def delete_fon(request, id):
    dataObject = DimFoncier.objects.get(id=id)
    if request.method == 'POST':

        dataObject.delete()
        return redirect('/foncier/DimFoncier/')
    context = {

        'item': dataObject, }
    return render(request, 'pag/delete_fon.html', context)


def DFG(request):
    if request.method == 'POST':
        form = Dimfong(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/foncier/DimFoncierGouvernanc/')
    else:
        form = Dimfong()

    return render(request, 'pag/DimFoncierGouvernanc.html', {'form': form, 'dataObject': DimFoncierGouvernanc.objects.all()})


# update Gouver
def update_up_Gouve(request, id):
    dataObject = DimFoncierGouvernanc.objects.get(id=id)
    form = Dimfong(instance=dataObject)
    if request.method == 'POST':
        form = Dimfong(request.POST, instance=dataObject)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/foncier/DimFoncierGouvernanc/')

    context = {

        'form': form

    }
    return render(request, 'pag/DimFoncierGouvernanc.html', context)


def delete_up_Gouve(request, id):
    dataObject = DimFoncierGouvernanc.objects.get(id=id)
    if request.method == 'POST':

        dataObject.delete()
        return redirect('/foncier/DimFoncierGouvernanc/')
    context = {

        'item': dataObject, }
    return render(request, 'pag/delete_fon.html', context)

foncier/templates/pag/DimFoncierGouvernanc.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
 <div class="row">
      <div class="col-md-12">
         <div class="card">
            <div class="card-header">
               <h5 class="form-title"><span>Gouvernance</span></h5>
            </div>
            {% include 'includes/messages.html' %}	
            <div class="card-body">
               <form method="POST" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  
                  <div class="text-right">
                     <button type="submit" class="btn custom-btn">Ajouter</button>
                   </div>
                   
               </form>
            </div>
         </div>
      </div>
   </div>
   
 <div class="content container-fluid">
    <div class="page-header">
       <div class="row align-items-center">
          
         
       </div>
    </div>
    {% include 'includes/messages.html' %}
    <div class="row">
       <div class="col-sm-12">
          <div class="card card-table">
             <div class="card-body">
                <div class="table-responsive">
                   <table id="table_id" class="table table-hover table-center mb-0">
                      <thead>
                         <tr>
                           <tr>
                              
                            <th>IdGouvFoncier</th>
                           
                              <th>codeCommune</th>
                              <th>nomCommune</th>
                              <th>LoiReglement</th>
                              <th>OutilSecuriseFoncie</th>
                              <th>ActFoncier</th>
                              <th>DegreConnaissanc</th>
                              <th>NivComprehension</th>
                              <th>Resume</th>
                              <th>AtelierBonInformat</th>
                              <th>SecuritAjout</th>
                              <th>NreConflitAnnComm</th>
                              <th>NbreIndustri_FoncComm</th>
                              <th>SuperfiAlloueIndustri </th>
                              <th>NbreIndustri_FoncCommMoy</th>
                              <th>SupTypeFoncier</th>
                              <th>ActImplique</th>
                              <th>CauseAvance</th>
                              <th>SolutionPropose</th>
                              <th>SolutionRetenu</th>
                              <th>VerificatProcedur</th>
                              <th>ControlPermanant</th>
                              <th>ConfliFoncieEnregMois</th>
                              <th>Date Début</th>
                              <th>Date de Modification</th>
                           <th class="text-right">Action</th>
                         </tr>
                      </thead>
                      <tbody>
                        {% for stud in dataObject %}
                         <tr>
                          
                            <td>{{ stud.id }}</td>
                              <td>{{stud.codeCommune}}</td>
                           <td>{{stud.nomCommune}}</td>
                           <td>{{stud.LoiReglement}}</td>
                           <td>{{stud.OutilSecuriseFoncie}}</td>
                           <td>{{stud.ActFoncier}}</td>
                           <td>{{stud.DegreConnaissanc}}</td>
                           <td>{{stud.NivComprehension}}</td>
                           <td>{{stud.Resume}}</td>
                           <td>{{stud.AtelierBonInformat}}</td>
                           <td>{{stud.SecuritAjout}}</td>
                           <td>{{stud.NreConflitAnnComm}}</td>
                           <td>{{stud.NbreIndustri_FoncComm}}</td>
                           <td>{{stud.SuperfiAlloueIndustri }}</td>
                           <td>{{stud.NbreIndustri_FoncCommMoy}}</td>
                           <td>{{stud.SupTypeFoncier}}</td>
                           <td>{{stud.ActImplique}}</td>
                           <td>{{stud.CauseAvance}}</td>
                           <td>{{stud.SolutionPropose}}</td>
                           <td>{{stud.SolutionRetenu}}</td>
                           <td>{{stud.VerificatProcedur}}</td>
                           <td>{{stud.ControlPermanant}}</td>
                           <td>{{stud.ConfliFoncieEnregMois}}</td>
                            <td>{{ stud.date_ent}}</td>
                            <td>{{ stud.date_modification }}</td>

                            <td class="text-right">
                               <div class="actions">
                                <a href="{% url 'foncier:up_Gouve' stud.id %}" class="btn btn-sm bg-success-light mr-2">
                                  <i class="fas fa-pen"></i>
                                  </a>
                                  <a href="{% url 'foncier:de_Gouve' stud.id %}" class="btn btn-sm bg-danger-light">
                                  <i class="fas fa-trash"></i>
                                  </a>
                               </div>
                            </td>
                         </tr>
                         {% endfor %}
                      </tbody>
                   </table>
                </div>
             </div>
          </div>
       </div>
    </div>

    
 </div>
 <style>
   /* Définir la couleur personnalisée pour le bouton */
   .custom-btn {
     background-color: #557029;
     border-color: #557029;
     color: #fff; /* Couleur du texte du bouton */
   }
 </style>

 {% endblock %}

foncier/templates/pag/DimGeographie.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
               <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                     <div class="col-12">
                        <h5 class="form-title"><span>Geographie</span></h5>
                     </div>

                     {% include 'includes/messages.html' %}	

                     <div class="col-sm-11">
                        <div class="form-group">
                           <label>code Commune </label>
                           {{ form.codeCommune }}</div>
                     </div>
                     <div class="col-sm-11">
                        <div class="form-group">
                           <label>nom Commune </label>
                           {{ form.nomCommune  }}</div>
                     </div>
                     <div class="col-sm-11">
                        <div class="form-group">
                           <label>Code Indicateur</label>
                           {{ form.CodeIndicateur }} </div>
                     </div>
                   <div class="col-sm-11">
                        <div class="form-group">
                           <label>Indicateur</label>
                           {{ form.Indicateur}}
                          </div>
                     </div>
                     <div class="col-sm-11">
                      <div class="form-group">
                         <label>Code Domaine </label>
                         {{ form.CodeDomaine }}
                        </div>
                   </div>
                   <div class="col-sm-11">
                    <div class="form-group">
                       <label>Nom Domaine</label>
                       {{ form.NomDomaine}}
                      </div>
                 </div>
                 <div class="col-sm-11">
                  <div class="form-group">

                     <label>Date Début</label>
                     {{ form.date}}
                    </div>
               </div>
               <div class="col-sm-11">
                  <div class="form-group">
                     <label>Date de Modification</label>
                     {{ form.date_modification }}
                    </div>
               </div>
                  
                 
                   </div>
                  
                   <br>
                     <div class="col-12">
                        <button type="submit" class="btn btn-primary">Ajouter</button>
                     </div>

               </form>
            </div>
         </div>
      </div>
      
<div >
 <div class="content container-fluid">
   <div class="page-header">
      <div class="row align-items-center">
      </div>
   </div>
   {% include 'includes/messages.html' %}
   <div class="row">
      <div class="col-sm-12">
         <div class="card card-table">
            <div class="card-body">
               <div class="table-responsive">
                  <table id="table_id" class="table table-hover table-center mb-0">
                     <thead>
                        <tr>
                           <th>ID</th>
                           <th>code Commune </th>
                           <th>nom Commune </th>
                           <th>Code Indicateur</th>
                           <th>Indicateur</th>
                           <th>CodeDomaine</th>
                           <th>NomDomaine</th>
                           <th>Date Début</th>
                           <th>Date de Modification</th>
                           
                           <th class="text-right">Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for stud in dataObject %}
                        <tr>
                         
                           <td>{{ stud.id }}</td>
                           <td>{{ stud.codeCommune  }}</td>

                           <td>{{ stud.nomCommune  }}</td>

                           <td>{{ stud.CodeIndicateur}}</td>

                           <td>{{ stud.Indicateur }}</td>
                           <td>{{ stud.CodeDomaine}}</td>

                           <td>{{ stud.NomDomaine }}</td>
                           <td>{{ stud.date }}</td>
                           <td>{{ stud.date_modification }}</td>
                           <td class="text-right">
                              <div class="actions">
                                 <a href="{% url 'foncier:up_geo' stud.id %}" class="btn btn-sm bg-success-light mr-2">
                                 <i class="fas fa-pen"></i>
                                 </a>
                                 <a href="{% url 'foncier:de_geo' stud.id %}" class="btn btn-sm bg-danger-light">
                                 <i class="fas fa-trash"></i>
                                 </a>
                              </div>
                           </td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>

   
</div>
{% endblock %}	

foncier/templates/pag/Dimfon.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
 <div class="row">
      <div class="col-md-12">
         <div class="card">
            <div class="card-header">
               <h5 class="form-title"><span>Foncier</span></h5>
            </div>
            {% include 'includes/messages.html' %}	
            <div class="card-body">
               <form method="POST" action="" enctype="multipart/form-data">
                  {% csrf_token %}
              
                  {{ form.as_p }}
                  
                  <div class="text-right">
                     <button type="submit" class="btn custom-btn">Ajouter</button>
                   </div>
               </form>
            </div>
         </div>
      </div>
   </div>
   
 <div class="content container-fluid">
    <div class="page-header">
       <div class="row align-items-center">
          
         
       </div>
    </div>
    {% include 'includes/messages.html' %}
    <div class="row">
       <div class="col-sm-12">
          <div class="card card-table">
             <div class="card-body">
                <div class="table-responsive">
                   <table id="table_id" class="table table-hover table-center mb-0">
                      <thead>
                         <tr>
                           <tr>
                            <th>IdFoncier</th>
                          
                           <th>nomCommune </th>
                           <th>codeCommune </th>
                           <th>StatuFoncier </th>
                           <th>TerrDeclas5D_Ans </th>
                           <th>ActFonciePresen </th>
                           <th>TxtFoncier </th>
                           <th>OutilGesFoncier </th>
                           <th>TypeConflit </th>
                           <th>TypeUsage </th>
                           <th>ExistCadrConcert </th>
                           <th>EchelCadrConcert </th>
                           <th>Entrepris_Indust_IncidFonc </th>
                           <th>TypeExploit_Foncier </th>
                           <th>SuperficConced  </th>
                           <th>SuperficExploite </th>
                           <th>Superfic_Deja_Exploite  </th>

                            <th>Date Début</th>
                            <th>Date de Modification</th>
                           <th class="text-right">Action</th>
                         </tr>
                      </thead>
                      <tbody>
                        {% for stud in dataObject %}
                         <tr>
                          
                            <td>{{ stud.id }}</td>
                           
                           <td>{{stud.nomCommune }}</td>
                           <td>{{stud.codeCommune }}</td>
                           <td>{{stud.StatuFoncier }}</td>
                           <td>{{stud.TerrDeclas5D_Ans }}</td>
                           <td>{{stud.ActFonciePresen }}</td>
                           <td>{{stud.TxtFoncier }}</td>
                           <td>{{stud.OutilGesFoncier }}</td>
                           <td>{{stud.TypeConflit }}</td>
                           <td>{{stud.TypeUsage }}</td>
                           <td>{{stud.ExistCadrConcert }}</td>
                           <td>{{stud.EchelCadrConcert }}</td>
                           <td>{{stud.Entrepris_Indust_IncidFonc }}</td>
                           <td>{{stud.TypeExploit_Foncier }}</td>
                           <td>{{stud.SuperficConced  }}</td>
                           <td>{{stud.SuperficExploite }}</td>
                           <td>{{stud.Superfic_Deja_Exploite  }}</td>

                             <td>{{ stud.date_en}}</td>
                             <td>{{ stud.date_modification }}</td>
                

                            <td class="text-right">
                               <div class="actions">
                                <a href="{% url 'foncier:up_fon' stud.id %}" class="btn btn-sm bg-success-light mr-2">
                                  <i class="fas fa-pen"></i>
                                  </a>
                                  <a href="{% url 'foncier:de_fon' stud.id %}" class="btn btn-sm bg-danger-light">
                                  <i class="fas fa-trash"></i>
                                  </a>
                               </div>
                            </td>
                         </tr>
                         {% endfor %}
                      </tbody>
                   </table>
                </div>
             </div>
          </div>
       </div>
    </div>
 
    
 </div>
 <style>
   /* Définir la couleur personnalisée pour le bouton */
   .custom-btn {
     background-color: #557029;
     border-color: #557029;
     color: #fff; /* Couleur du texte du bouton */
   }
 </style>

 {% endblock %}	

foncier/templates/pag/delete_fon.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'foncier:de_fon' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'foncier:DimFoncier'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                               </section>
<div >
 </div>
   
</div>
{% endblock %}	

foncier/templates/pag/delete_geo.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'foncier:de_geo' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'foncier:DimGeographie'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div> </section>
<div >
 </div>
   
</div>
{% endblock %}	