Stud/urls.py
from django.urls import include


from .import views
from django.contrib import admin
from django.urls import path
from .import Hod_views, views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin', admin.site.urls),
    path('base', views.Base, name='base'),
    path('home', Hod_views.Home, name='home'),
    path('', views.Accueil, name='acceueil'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('gestionnaire', views.coord, name='gestionnaire'),
    path('decideur', views.deci, name='decideur'),
    path('visiteur', views.visit, name='visiteur'),
    path('peche/', views.peche, name="peche"),
    path('post/<int:id>/', views.detail, name="detail"),
    path('post/', views.all, name="post"),
    path('new_post', views.new_post, name="new_post"),
    path('update_post/<int:pk>/', views.update_post, name="update_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),

    path('ressource/', views.ress, name="ressource"),
    path('upda_res/<int:id>/', views.upda_ress, name="upda_res"),
    path('delete_ress/<int:id>/', views.del_ress, name="delete_ress"),
    path('foncier', views.fonce, name='foncier'),
    path('commune', views.commune, name='commune'),
    path('commune_detail', views.co, name='commune_detail'),
    path('foncier/', include('foncier.urls')),

    # profile

    path('profile_list/', views.profile_list, name='profile_list'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foncier/urls.py
from django.urls import path

from .import views

app_name = 'foncier'


urlpatterns = [
    path('DimFoncier/', views.DimFon, name='DimFoncier'),
    path('DimFoncierGouvernanc/', views.DFG, name='DimFoncierGouvernanc'),
   # path('DimGeographie/', views.DG, name='DimGeographie'),
   # path('FactFoncier/', views.FF, name='FactFoncier'),
  
    path('de_fon<int:id>/', views.delete_fon, name='de_fon'),
    path('up_fon<int:id>/', views.update_fon, name='up_fon'),
    path('de_Gouve<int:id>/', views.delete_up_Gouve, name='de_Gouve'),
    path('up_Gouve<int:id>/', views.update_up_Gouve, name='up_Gouve'),
   # path('up_geo<int:id>/', views.update_geo, name='up_geo'),
    #path('de_geo<int:id>/', views.delete_geo, name='de_geo'),


]

templates/includes/chart.html
<script>
  'use strict';
  $(document).ready(function() {

    var options = {
      series: [{{dt}}, {{datg}}],
      chart: {
        height: 350,
        width: '100%',
      type: 'donut',
    },
    plotOptions: {
      pie: {
        startAngle: -90,
        endAngle: 270
      }
    },
    dataLabels: {
      enabled: false
    },
    fill: {
      type: 'gradient',
    },
    legend: {
      formatter: function(val, opts) {
        return val + " - " + opts.w.globals.series[opts.seriesIndex]
      }
    },

    responsive: [{
      breakpoint: 480,
      options: {
        chart: {
          height: 350,
          width: '100%',
        },
        legend: {
          position: 'bottom'
        }
      }
    }]
    };

    var chart = new ApexCharts(document.querySelector("#course"), options);
    chart.render();



      var options = {
          series: [{{dt}}, {{datg}}],
          chart: {
            height: 350,
            width: '100%',
          type: 'pie',
        },
        labels:[{{dt}}, {{datg}}],
        responsive: [{
          breakpoint: 480,
          options: {
            chart: {
              height: 350,
              width: '100%',
            },
            legend: {
              position: 'bottom'
            }
          }
        }]
        };

        var chart = new ApexCharts(document.querySelector("#all_details"), options);
        chart.render();





      if ($('#stud_gender').length > 0) {
          var optionsBar = {
              chart: {
                  type: 'bar',
                  height: 350,
                  width: '100%',
                  stacked: true,
                  toolbar: {
                      show: false
                  },
              },
              dataLabels: {
                  enabled: false
              },
              plotOptions: {
                  bar: {
                      columnWidth: '45%',
                  }
              },
              series: [
              {
                  name: "Foncier",
                  color: '#fdbb38',
                  data: [{{dt}}],
              },


              {
                  name: "Gouvernance",
                  color: '#18affb',
                  data: [{{datg}}],
              },
            

              ],
              labels: [2023],
              xaxis: {
                  labels: {
                      show: false
                  },
                  axisBorder: {
                      show: false
                  },
                  axisTicks: {
                      show: false
                  },
              },
              yaxis: {
                  axisBorder: {
                      show: false
                  },
                  axisTicks: {
                      show: false
                  },
                  labels: {
                      style: {
                          colors: '#777'
                      }
                  }
              },
              title: {
                  text: '',
                  align: 'left',
                  style: {
                      fontSize: '18px'
                  }
              }

          }

          var chartBar = new ApexCharts(document.querySelector('#stud_gender'), optionsBar);
          chartBar.render();
          }
		  
		  
		  
			if ($('#apexcharts-area').length > 0) {
	var options = {
		chart: {
			height: 350,
			type: "area",
			toolbar: {
				show: false
			},
		},
		dataLabels: {
			enabled: false
		},
		stroke: {
			curve: "smooth"
		},
		series: [{
			name: "Foncier",
			data: [{{dt}}]
		}, {
			name: "Gouvernance",
			color: '#FFBC53',
			data: [{{datg}}]
		}],
		xaxis: {
			categories: [],
		}
	}
	
	var chart = new ApexCharts(
		document.querySelector("#apexcharts-area"),
		options
	);
	chart.render();
	}
		  

  });

</script>

templates/includes/footer.html
{% load static %}
<footer style="background-color: #000;">
   <div class="container">
     <div class="row">
       <div class="col-xl-4 col-sm-6 col-12 footer-column">
         <div class="footer-links">
           <ul style="font-size: 30px; color: #fff;">
             <li><img class="vector-icon21" alt="" src="{% static '/public/vector14.svg'%}" />&nbsp;&nbsp;<a href="{% url 'acceueil' %}" style="color:#fff;">Accueil</a></li>
             <li><img class="vector-icon22" alt="" src="{% static '/public/vector15.svg'%}" />&nbsp;&nbsp;<a href="{% url 'commune' %}" style="color:#fff;">Commune</a></li>
             <li><img class="vector-icon23" alt="" src="{% static '/public/vector16.svg'%}" />&nbsp;&nbsp;<a href="{% url 'ressource' %}" style="color:#fff;">Ressources</a></li>
             <li><img class="vector-icon24" alt="" src="{% static '/public/vector17.svg'%}" />&nbsp;&nbsp;<a href="{% url 'post' %}" style="color:#fff;">Blog</a></li>
           </ul>
         </div>
       </div>
       <div class="col-xl-4 col-sm-6 col-12 footer-column">
         <div class="column" style="margin-right: 30px;">
           <p style="color:#a3bc1c; font-size: 20px;">Nombre total de visites : {{ request.session.visits }}</p>
           <h6><p style="color: #fff; font-size: 20px;">Mairie de Darou khoudoss</p></h6>
           <p style="color: #fff; font-size: 20px;"><i class="fa-regular fa-envelope"></i> &nbsp;&nbsp;darou@sentoo.sn</p>
           <p style="color: #fff; font-size: 20px;"> Boîte postale:BP 167</p>
          
           <p style="color: #fff; font-size: 20px;"><i class="fa-solid fa-phone"></i>&nbsp;&nbsp;+221 33 0000000</p>
           <p style="color: #fff; font-size: 20px;">http://www.daroukhoudouss.sn</p>
         </div>
       </div>
       <div class="col-xl-4 col-sm-6 col-12 footer-column">
         <div class="column" style="margin-left: 50px;">
           <h3 style="color: #fff;">Suivez-nous</h3>
           <ul style="color: #fff;">
             <li><img class="vector-icon25" alt="" src="{% static '/public/vector18.svg'%}" />&nbsp;&nbsp;&nbsp;<a href="#" style="color: #fff;font-size: 20px;">Facebook</a></li><br>
             <li><img class="vector-icon26" alt="" src="{% static '/public/vector19.svg'%}" />&nbsp;&nbsp;&nbsp;<a href="#" style="color: #fff;font-size: 20px;">Twitter</a></li><br>
             <li><img class="vector-icon26" alt="" src="{% static '/public/vector20.svg'%}" />&nbsp;&nbsp;&nbsp;<a href="#" style="color: #fff;font-size: 20px;">LinkedIn</a></li>
           </ul>
         </div>
       </div>
     </div>
     <p style="color: #fff; font-size: 20px;">Copyright © 2023 Precvadi <span style="color:#a3bc1c; font-size: 20px;">ENSA-APHRC</span></p>
           
   </div>
 </footer>
 <style>
   .footer-column {
     border-right: 2px solid #fff; /* Couleur de la bordure entre les colonnes */
     padding-right: 15px; /* Espace entre la bordure et le contenu de chaque colonne */
   }
 
   /* Pour la dernière colonne, supprimez la bordure de droite pour éviter un double trait */
   .footer-column:last-child {
     border-right: none;
   }
 </style>

templates/includes/header.html
{% load static %}
<div class="header">
  <div class="header-left">
    <a href="{% url 'acceueil' %}" class="logo">
      <img src="{% static 'assets/img/logo.jpg' %}" alt="Logo" />
    </a>
    <a href="{% url 'acceueil' %}" class="logo logo-small">
      <img
        src="{% static 'assets/img/log.jpg' %}"
        alt="Logo"
        width="30"
        height="30"
      />
    </a>
  </div>
  <a href="javascript:void(0);" id="toggle_btn">
    <i class="fas fa-align-left"></i>
  </a>
  <div class="top-nav-search"></div>
  <a class="mobile_btn" id="mobile_btn">
    <i class="fas fa-bars"></i>
  </a>

  <ul class="nav user-menu">
    {% if not request.user.userprofile %}
    <li><a href="{% url 'create_profile' %}">Complétez votre Profil</a></li>
    {% endif %}
    <li class="nav-item dropdown has-arrow">
      <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
        <span class="user-img">
          <img
            src="{{ request.user.userprofile.profile_picture.url }}"
            alt="User Image"
            width="50"
            height="50"
          />
        </span>
      </a>
      <div class="dropdown-menu">
        <div class="user-header">
          <div class="avatar avatar-sm">
            <span class="user-img">
              <img
                src="{{ request.user.userprofile.profile_picture.url }}"
                alt="User Image"
                width="50"
                height="50"
              />
            </span>
          </div>
          <div class="user-text">
            <h6>
              {{ request.user.userprofile.first_name }}
              {{request.user.userprofile.last_name }}
            </h6>
          </div>
        </div>
        {% if not request.user.userprofile %}
        <a class="dropdown-item" href="{% url 'create_profile' %}"
          >Ajouter un Profil</a
        >
        {% else %}
        <a class="dropdown-item" href="{% url 'profile_list' %}">Profil</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'logout' %}">Se déconnecter</a>
      </div>
    </li>
  </ul>
</div>

templates/includes/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% if messages %}
{% for message in messages %}
{% if message.tags == 'warning' %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}                        
								
								
	

templates/includes/sidebar.html
{% load active_link_tags %}
{% load static %}
<div class="sidebar" id="sidebar"  style="background-color: #557029;">
    <div class="sidebar-inner slimscroll">
       <div id="sidebar-menu" class="sidebar-menu">

         <ul>
            <li class="menu-title">
               <span>{{ user.first_name}} {{ user.last_name}}</span>
            </li>
            <li class="menu-title">
               <span>Menu principal</span>
            </li>

          
   
  

   
					<li class="{% active_link 'home' 'active' %}">
              <a href="{% url 'home' %}"><img src="{% static '/imge/icon foncier.jpg'%}" width="40" height="40"> <span style="font-size: 20px">Foncier</span></a>
           </li>
           <li class="submenu {% active_link 'add_student' 'active' %} {% active_link 'view_student' 'active' %}">
               

               


               <li><a href="{% url 'foncier:DimFoncier' %}">Foncier</a></li>
               <li><a href="{% url 'foncier:DimFoncierGouvernanc' %}">Gouvernance</a></li>
        
               <li><i class=""></i>
                          <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> <span> Se déconnecter</span></a>
               </li>
               
            </li>
        

            </li>
         </ul>

       </div>
    </div>
 </div>